name: Release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Deps fro Pypi Release
        run: |
          pip3 -q install setuptools wheel twine
          pip3 -q install -r requirements.txt
      - name: Publish to pypi
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python3 setup.py sdist bdist_wheel
          twine upload dist/*
      - name: Upload Wheel and Source Dist to Github Releases
        uses: softprops/action-gh-release@v1
        with:
          name: Agrothon-Client Release ${{ steps.get_version.outputs.VERSION }}
          files: |
            dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
